image: maven:3-jdk-8
stages:
 - test
 - build
services:
- 'mysql:5.5'
variables:
  MYSQL_USER: app_root
  MYSQL_CI_URL: jdbc:mysql://mysql/movieDb
  MYSQL_PASSWORD: root123
  MYSQL_DATABASE: movieDb
  MYSQL_ROOT_PASSWORD: root

maven-test:
  stage: test
  script: "mvn test -B"    

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
          
